
#userspace:
all:
	#gcc -v -Wall usa_libnl_ex.c -lnl-3 -o test_libnl -L/usr/include/libnl3 -I/usr/include/libnl3
	gcc -Wall usa_libnl_ex.c -lnl-3 -o test_libnl -L/usr/include/libnl3 -I/usr/include/libnl3

clean:
	rm -rf *~ test_libnl
